config/routes.rb
Rails.application.routes.draw do
  get "archives/index"

  resources :entries
  root to: "entries#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  validates :calories, :proteins, :carbohydrates, :fats, :meal_type, presence: true

  def day
    self.created_at.strftime("%b %e, %Y")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
    @entries = Entry.all.group_by(&:day)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[show edit update destroy]

  # GET /entries or /entries.json
  def index
    @entries = Entry.where("created_at >= ?", Date.today)
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy!

    respond_to do |format|
      format.html { redirect_to entries_path, status: :see_other, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:meal_type, :calories, :proteins, :carbohydrates, :fats)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/archives/index.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-half">
    <% @entries.each do |day, entries| %>
      <h3 class="is-size-4 has-text-weight-bold mb-4 has-text-centered">Entries for <%= day %></h3>
      <nav class="level is-mobile">
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Calories</p>
            <p class="title"><%= entries.pluck(:calories).sum %>kcal</p>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Proteins</p>
            <p class="title"><%= entries.pluck(:proteins).sum %>g</p>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Carbohydrates</p>
            <p class="title"><%= entries.pluck(:carbohydrates).sum %>g</p>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Fats</p>
            <p class="title"><%= entries.pluck(:fats).sum %>g</p>
          </div>
        </div>
      </nav>
      <% entries.each do |entry| %>
        <%= link_to entry_path(entry) do %>
          <div class="card">
            <div class="card-content">
              <strong><%= entry.meal_type %></strong><br/>
              <%= entry.calories %> calories, 
              <%= entry.proteins %> g protein, 
              <%= entry.carbohydrates %> g carbs, 
              <%= entry.fats %> g fat
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/entries/_entry.html.erb
<div id="<%= dom_id entry %>" class="box p-4 mb-4">
  <h2 class="title is-4 has-text-centered mb-5">Nutritional Information</h2>
  <div class="content mt-4">
    <p>
      <strong>Meal type:</strong>
      <span class="has-text-weight-semibold"><%= entry.meal_type %></span>
    </p>
    <p>
      <strong>Calories:</strong>
      <span class="has-text-weight-semibold"><%= entry.calories %></span>
    </p>
    <p>
      <strong>Proteins:</strong>
      <span class="has-text-weight-semibold"><%= entry.proteins %> g</span>
    </p>
    <p>
      <strong>Carbohydrates:</strong>
      <span class="has-text-weight-semibold"><%= entry.carbohydrates %> g</span>
    </p>
    <p>
      <strong>Fats:</strong>
      <span class="has-text-weight-semibold"><%= entry.fats %> g</span>
    </p>
  </div>
</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry, local: true) do |form| %>
  <% if entry.errors.any? %>
    <div class="message is-danger">
      <div class="message-header">
        <p><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</p>
      </div>
      <div class="message-body">
        <ul>
          <% entry.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :meal_type, class: "label" %>
    <%= form.text_field :meal_type, class: "input" %>
  </div>
  <div class="field">
    <%= form.label :calories, class: "label" %>
    <%= form.number_field :calories, class: "input" %>
  </div>
  <div class="field">
    <%= form.label :proteins, class: "label" %>
    <%= form.number_field :proteins, class: "input" %>
  </div>
  <div class="field">
    <%= form.label :carbohydrates, class: "label" %>
    <%= form.number_field :carbohydrates, class: "input" %>
  </div>
  <div class="field">
    <%= form.label :fats, class: "label" %>
    <%= form.number_field :fats, class: "input" %>
  </div>
  <div class="actions">
    <%= form.submit class: "button is-success" %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third">
    <h1 class="is-size-2 has-text-weight-bold mb-3">Editing entry</h1>
    <%= render "form", entry: @entry %>
  </div>
</div>

app/views/entries/index.html.erb
<% content_for :title do %>
  Foodlog <%= DateTime.now.strftime("%B %e, %Y") %>
<% end %>
<div class="columns is-multiline mt-6 is-centered">
  <% @entries.each do |entry| %>
    <div class="column is-one-quarter">
      <div class="card has-background-light">
        <header class="card-header has-background-primary has-text-white">
          <p class="card-header-title is-centered">
            <%= entry.meal_type %>
          </p>
        </header>
        <div class="card-content">
          <div class="content has-text-left">
            <p><span class="has-text-weight-bold"><%= entry.calories %></span> calories</p>
            <p><span class="has-text-weight-bold"><%= entry.proteins %></span> grams of protein</p>
            <p><span class="has-text-weight-bold"><%= entry.carbohydrates %></span> grams of carbohydrates</p>
            <p><span class="has-text-weight-bold"><%= entry.fats %></span> grams of fat</p>
            <p class="is-italic has-text-grey">Logged <%= time_ago_in_words(entry.created_at) %> ago</p>
          </div>
        </div>
        <footer class="card-footer">
          <%= link_to 'Show', entry, class: 'card-footer-item button is-link is-light' %>
          <%= link_to 'Edit', edit_entry_path(entry), class: 'card-footer-item button is-warning is-light' %>
          <%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' }, class: 'card-footer-item button is-danger is-light' %>
        </footer>
      </div>
    </div>
  <% end %>
</div>
<div class="columns is-centered mt-6">
  <%= link_to "View all entries", archives_index_path, class: "button is-link is-outlined is-centered" %>
</div>

app/views/entries/new.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third">
    <h1 class="is-size-2 has-text-weight-bold mb-3">New entry</h1>
    <%= render 'form', entry: @entry %>
  </div>
</div>

app/views/entries/show.html.erb
<%= render @entry %>
<div class="buttons mt-4">
  <%= link_to "Edit this entry", edit_entry_path(@entry), class: "button is-info" %>
  <%= link_to "Back to entries", entries_path, class: "button is-light" %>
  <%= button_to "Destroy this entry", @entry, method: :delete, class: "button is-danger", data: { confirm: "Are you sure you want to delete this entry?" } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css"
>
      <meta name="apple-mobile-web-app-capable" content="yes">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= yield :head %>
      <link rel="manifest" href="/manifest.json">
      <link rel="icon" href="/icon.png" type="image/png">
      <link rel="icon" href="/icon.svg" type="image/svg+xml">
      <link rel="apple-touch-icon" href="/icon.png">
      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
      <%= javascript_importmap_tags %>
    </head>
    <body>
      <%= render "shared/header" %>
      <% if notice.present? %>
        <div class="notification is-alert is-light">
          <%= notice %>
        </div>
      <% end %>
      <% if alert.present? %>
        <div class="notification is-danger is-light">
          <%= alert %>
        </div>
      <% end %>
      <div class="container">
        <%= yield %>
      </div>
    </body>
  </html>

app/views/shared/_header.html.erb
<section class="hero is-link is-small">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <header class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to root_path, class: "navbar-item" do%>
            <span class="has-text-weight-bold is-size-4 ml-4">Foodlog</span>
          <%end%>
          <span class="navbar-burger" data-target="navbarMenuHeroC">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroC" class="navbar-menu">
          <div class="navbar-end">
            <span>
              <%= link_to "Create new entry", new_entry_path, class:"button is-success mt-4" %>
            </span>
          </div>
        </div>
      </div>
    </header>
  </div>
  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <p class="title">
        <% if content_for(:title) %>
          <%= yield :title %>
        <% else %>
          Foodlog
        <% end %>
      </p>
    </div>
  </div>
  <!-- Hero footer: will stick at the bottom -->
</section>